# Generated by Django 3.2.3 on 2021-05-23 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sess_id', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_1', models.CharField(max_length=1)),
                ('cell_2', models.CharField(max_length=1)),
                ('cell_3', models.CharField(max_length=1)),
                ('cell_4', models.CharField(max_length=1)),
                ('cell_5', models.CharField(max_length=1)),
                ('cell_6', models.CharField(max_length=1)),
                ('cell_7', models.CharField(max_length=1)),
                ('cell_8', models.CharField(max_length=1)),
                ('cell_9', models.CharField(max_length=1)),
                ('game', models.BooleanField(default=False)),
                ('game_state', models.CharField(default='0', max_length=2)),
                ('turn', models.CharField(default='0', max_length=2)),
                ('sess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoegame.session')),
            ],
        ),
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('connected', models.BooleanField(default=False)),
                ('p1_nm', models.CharField(default='null', max_length=20)),
                ('p2_nm', models.CharField(default='null', max_length=20)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 5, 23, 10, 57, 28, 441347, tzinfo=utc))),
                ('reset', models.BooleanField(default=False)),
                ('sess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoegame.session')),
            ],
        ),
    ]
