# Generated by Django 3.2.3 on 2021-05-23 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoegame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 10, 57, 54, 314637, tzinfo=utc)),
        ),
    ]
