# Generated by Django 3.2.3 on 2021-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoegame', '0004_auto_20210523_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='game_state',
            field=models.CharField(default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='status',
            name='turn',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
