# Generated by Django 3.2.3 on 2021-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoegame', '0005_auto_20210523_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='turn',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
